/**
 * AES-256-GCM for credential secrets.
 *
 * This file has a twin: backend/app/core/secrets.py. They must agree byte for
 * byte, because Next.js encrypts a token and Python is what later decrypts it
 * to call GitHub. Any change here needs the same change there, and
 * backend/tests/test_secrets.py pins a ciphertext produced by THIS file so the
 * two can never drift silently.
 *
 * Wire format, one text column:
 *
 *     v1.<base64url(nonce)>.<base64url(ciphertext || tag)>
 *
 * Three deliberate choices:
 *
 * - `v1.` so a future algorithm or key rotation is a clean failure rather than
 *   a garbage decrypt.
 * - Dotted base64url parts rather than one packed blob: readable in psql, and
 *   no off-by-one slicing bugs between two languages.
 * - The tag is APPENDED to the ciphertext, which is what Python's AESGCM
 *   returns natively. Node keeps them separate (`cipher.getAuthTag()`), so this
 *   side does the concatenating. That asymmetry is the single most likely bug
 *   in this file — the trailing 16 bytes are the tag, always.
 *
 * No AAD: the row id is generated by Postgres (`defaultRandom()`) and so is not
 * known at encrypt time, and the threat this guards against — someone reading
 * the database — is not one AAD addresses.
 *
 * Server-only, by the same convention as the rest of lib/server/: the
 * `node:crypto` import below cannot resolve in a browser bundle, so a stray
 * client import fails loudly at build time rather than shipping a decrypt
 * routine to the browser.
 */

import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";

const VERSION = "v1";
const KEY_BYTES = 32; // AES-256
const NONCE_BYTES = 12; // GCM standard
const TAG_BYTES = 16;

export class CredentialCryptoError extends Error {}

/**
 * Read the key lazily, not at module load: an unset key should surface as a
 * clear error from the one endpoint that needs it, not crash every route that
 * happens to import this module.
 */
function key(): Buffer {
  const raw = process.env.CREDENTIALS_ENCRYPTION_KEY;
  if (!raw) {
    throw new CredentialCryptoError(
      "CREDENTIALS_ENCRYPTION_KEY is not set. Generate one with " +
        `node -e "console.log(require('crypto').randomBytes(32).toString('base64'))" ` +
        "and put the SAME value in frontend/.env.local and backend/.env.",
    );
  }

  const decoded = Buffer.from(raw, "base64");
  if (decoded.length !== KEY_BYTES) {
    throw new CredentialCryptoError(
      `CREDENTIALS_ENCRYPTION_KEY must decode to ${KEY_BYTES} bytes, got ${decoded.length}. ` +
        "It should be base64 of 32 random bytes.",
    );
  }
  return decoded;
}

function b64url(buffer: Buffer): string {
  return buffer.toString("base64url");
}

export function encryptSecret(plaintext: string): string {
  if (!plaintext) {
    throw new CredentialCryptoError("Refusing to encrypt an empty secret.");
  }

  const nonce = randomBytes(NONCE_BYTES);
  const cipher = createCipheriv("aes-256-gcm", key(), nonce);
  const ciphertext = Buffer.concat([
    cipher.update(plaintext, "utf8"),
    cipher.final(),
  ]);

  // Python's AESGCM.encrypt() returns ciphertext||tag. Match that shape here so
  // one format serves both languages.
  const payload = Buffer.concat([ciphertext, cipher.getAuthTag()]);

  return `${VERSION}.${b64url(nonce)}.${b64url(payload)}`;
}

export function decryptSecret(blob: string): string {
  const parts = blob.split(".");
  if (parts.length !== 3) {
    throw new CredentialCryptoError("Malformed secret: expected three dotted parts.");
  }

  const [version, nonceB64, payloadB64] = parts;
  if (version !== VERSION) {
    throw new CredentialCryptoError(
      `Unsupported secret version "${version}". This build understands ${VERSION}.`,
    );
  }

  const nonce = Buffer.from(nonceB64, "base64url");
  const payload = Buffer.from(payloadB64, "base64url");
  if (nonce.length !== NONCE_BYTES || payload.length <= TAG_BYTES) {
    throw new CredentialCryptoError("Malformed secret: bad nonce or payload length.");
  }

  const ciphertext = payload.subarray(0, payload.length - TAG_BYTES);
  const tag = payload.subarray(payload.length - TAG_BYTES);

  const decipher = createDecipheriv("aes-256-gcm", key(), nonce);
  decipher.setAuthTag(tag);

  try {
    return Buffer.concat([
      decipher.update(ciphertext),
      decipher.final(),
    ]).toString("utf8");
  } catch {
    // final() throws when the tag does not verify: wrong key, or tampering.
    throw new CredentialCryptoError(
      "Could not decrypt the stored secret. CREDENTIALS_ENCRYPTION_KEY has " +
        "probably changed since it was saved — delete the credential and add it again.",
    );
  }
}

/** The visible tail of a token, for identifying it without decrypting. */
export function lastFourOf(secret: string): string {
  return secret.slice(-4);
}
