"""AES-256-GCM for credential secrets.

This file has a twin: frontend/lib/server/crypto.ts. They must agree byte for
byte, because Next.js is what encrypts a token and this side is what decrypts it
to call GitHub. Any change here needs the same change there, and
tests/test_secrets.py pins a ciphertext produced by the TypeScript side so the
two can never drift silently.

Wire format, one text column::

    v1.<base64url(nonce)>.<base64url(ciphertext || tag)>

The tag placement is the thing to be careful about. ``AESGCM.encrypt`` returns
``ciphertext || tag`` already concatenated, which is the shape this format
adopts; Node returns the two separately and has to join them. Decrypting here is
therefore a straight pass to ``AESGCM.decrypt``, and the trailing 16 bytes are
never sliced off by hand.

No AAD: the row id is generated by Postgres, so it is not known at encrypt time,
and the threat this guards against — someone reading the database — is not one
AAD addresses.
"""

import base64
import os

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from app.core.config import Settings

VERSION = "v1"
KEY_BYTES = 32  # AES-256
NONCE_BYTES = 12  # GCM standard


class CredentialCryptoError(Exception):
    """Raised for a missing key, a malformed blob, or a failed decrypt."""


def _b64url_decode(value: str) -> bytes:
    # base64url without padding is what Node's toString("base64url") emits.
    padding = "=" * (-len(value) % 4)
    try:
        return base64.urlsafe_b64decode(value + padding)
    except Exception as exc:  # noqa: BLE001 - surfaced as one clear error below
        raise CredentialCryptoError("Malformed secret: bad base64url.") from exc


def _b64url_encode(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).decode("ascii").rstrip("=")


def _key(settings: Settings) -> bytes:
    raw = settings.credentials_encryption_key
    if not raw:
        raise CredentialCryptoError(
            "CREDENTIALS_ENCRYPTION_KEY is not set. Generate one with "
            "`node -e \"console.log(require('crypto').randomBytes(32)"
            '.toString(\'base64\'))"` and put the SAME value in '
            "frontend/.env.local and backend/.env."
        )

    try:
        decoded = base64.b64decode(raw, validate=True)
    except Exception as exc:  # noqa: BLE001
        raise CredentialCryptoError(
            "CREDENTIALS_ENCRYPTION_KEY is not valid base64."
        ) from exc

    if len(decoded) != KEY_BYTES:
        raise CredentialCryptoError(
            f"CREDENTIALS_ENCRYPTION_KEY must decode to {KEY_BYTES} bytes, got "
            f"{len(decoded)}. It should be base64 of 32 random bytes."
        )
    return decoded


def encrypt_secret(plaintext: str, settings: Settings) -> str:
    """Encrypt a token. Mirrors encryptSecret() in crypto.ts.

    Empty is a mistake worth failing on: a credential whose secret is ``""`` is
    not a credential, and the row would look complete.
    """
    if not plaintext:
        raise CredentialCryptoError("Refusing to encrypt an empty secret.")

    return encrypt_value(plaintext, settings)


def encrypt_value(plaintext: str, settings: Settings) -> str:
    """The same envelope and key, but ``""`` is allowed. Mirrors encryptValue().

    Project environment variables use this one: ``KEY=`` is a real line in a real
    ``.env``, and refusing it would silently drop a variable from the file the
    container is given. AES-GCM over an empty plaintext is well defined — the
    payload is then exactly the 16-byte tag, which ``AESGCM.decrypt`` has always
    accepted here (there is no payload length check on this side).
    """
    nonce = os.urandom(NONCE_BYTES)
    # Returns ciphertext || tag, which is exactly what the format stores.
    payload = AESGCM(_key(settings)).encrypt(nonce, plaintext.encode("utf-8"), None)
    return f"{VERSION}.{_b64url_encode(nonce)}.{_b64url_encode(payload)}"


def decrypt_secret(blob: str, settings: Settings) -> str:
    """Decrypt a token written by either side. Mirrors decryptSecret()."""
    parts = blob.split(".")
    if len(parts) != 3:
        raise CredentialCryptoError("Malformed secret: expected three dotted parts.")

    version, nonce_b64, payload_b64 = parts
    if version != VERSION:
        raise CredentialCryptoError(
            f"Unsupported secret version {version!r}. This build understands {VERSION}."
        )

    nonce = _b64url_decode(nonce_b64)
    payload = _b64url_decode(payload_b64)
    if len(nonce) != NONCE_BYTES:
        raise CredentialCryptoError("Malformed secret: bad nonce length.")

    try:
        return AESGCM(_key(settings)).decrypt(nonce, payload, None).decode("utf-8")
    except InvalidTag as exc:
        raise CredentialCryptoError(
            "Could not decrypt the stored secret. CREDENTIALS_ENCRYPTION_KEY has "
            "probably changed since it was saved — delete the credential and add "
            "it again."
        ) from exc


def mask(secret: str) -> str:
    """A log-safe rendering. Never log a token, even a short one."""
    return f"••••{secret[-4:]}" if len(secret) >= 4 else "••••"
